### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by sdgandhi** [Syntertainment/SYNUtils#2]
- [x] Verify that the dynamic framework scheme is "shared"
- [x] Add Carthage badge:

`[![Carthage compatible](https://img.shields.io/badge/Carthage-compatible-4BC51D.svg?style=flat)](https://github.com/Carthage/Carthage)`

**Comment by jhurliman** [comment]
Completed the two above tasks. Don't we need to add a Cartfile and publish the first release though?

**Comment by sdgandhi** [comment]
@jhurliman nope, anyone can now pull in this library by adding `Syntertainment/SYNUtils` to their cartfile. We don't need to add anything to the repo.
